//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserRole
    {
        public string UserId { get; set; }
        public string RoleId { get; set; }
        public Nullable<long> Loc_Auth_Id { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual tbl_LocationAuthentication tbl_LocationAuthentication { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
