//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SetupAuthentication
    {
        public long Id { get; set; }
        public long Loc_Auth_Id { get; set; }
        public Nullable<bool> ChangePassword { get; set; }
        public Nullable<bool> AddUsers { get; set; }
        public Nullable<bool> UsersAuthentication { get; set; }
        public Nullable<bool> Reports { get; set; }
        public Nullable<bool> ProductionOrderStatusReport { get; set; }
        public Nullable<bool> LostOpporTunitySalesReport { get; set; }
    
        public virtual tbl_LocationAuthentication tbl_LocationAuthentication { get; set; }
    }
}
