//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EODFile
    {
        public long SNO { get; set; }
        public string CompanyId { get; set; }
        public string TerminalId { get; set; }
        public string LocationId { get; set; }
        public string EODID { get; set; }
        public byte[] FileByte { get; set; }
    }
}
