//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LocationAuthentication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_LocationAuthentication()
        {
            this.AspNetUserRoles = new HashSet<AspNetUserRole>();
            this.tbl_EnquiryAuthentication = new HashSet<tbl_EnquiryAuthentication>();
            this.tbl_MasterDataAuthentication = new HashSet<tbl_MasterDataAuthentication>();
            this.tbl_SetupAuthentication = new HashSet<tbl_SetupAuthentication>();
            this.tbl_TrasactionsAuthentication = new HashSet<tbl_TrasactionsAuthentication>();
        }
    
        public long Id { get; set; }
        public string UserId { get; set; }
        public string User_Locations { get; set; }
        public string Manager_Locations { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EnquiryAuthentication> tbl_EnquiryAuthentication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MasterDataAuthentication> tbl_MasterDataAuthentication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SetupAuthentication> tbl_SetupAuthentication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TrasactionsAuthentication> tbl_TrasactionsAuthentication { get; set; }
    }
}
