//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseOrder
    {
        public string DocumentID { get; set; }
        public string CompanyID { get; set; }
        public string LocationID { get; set; }
        public string StorageID { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string VendorID { get; set; }
        public string PODescription { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetValue { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public int Dataid { get; set; }
        public string POStatus { get; set; }
        public string ReferID { get; set; }
    
        public virtual tbl_Company tbl_Company { get; set; }
        public virtual tbl_Location tbl_Location { get; set; }
        public virtual tbl_PurchaseOrder tbl_PurchaseOrder1 { get; set; }
        public virtual tbl_PurchaseOrder tbl_PurchaseOrder2 { get; set; }
        public virtual tbl_Vendor tbl_Vendor { get; set; }
    }
}
