//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ImageDetails
    {
        public int ImageDetailsID { get; set; }
        public string Type { get; set; }
        public string ID { get; set; }
        public string FileName { get; set; }
        public System.DateTime RowCreatedDate { get; set; }
    }
}
