//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransfterDisplayDateTime
    {
        public long ID { get; set; }
        public string LocationID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.TimeSpan> Warning1 { get; set; }
        public Nullable<System.TimeSpan> Warning2 { get; set; }
        public Nullable<System.TimeSpan> Warning3 { get; set; }
        public Nullable<bool> Warning1Status { get; set; }
        public Nullable<bool> Warning2Status { get; set; }
        public Nullable<bool> Warning3Status { get; set; }
        public string TDDocumentID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> WLDbStatus { get; set; }
        public Nullable<bool> LDbStatus { get; set; }
        public Nullable<System.DateTime> SysDateTime { get; set; }
        public Nullable<bool> TDDocumentIDStatus { get; set; }
    }
}
