//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EOD
    {
        public string LocationID { get; set; }
        public string TerminialID { get; set; }
        public string EODID { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<decimal> Loan { get; set; }
        public Nullable<decimal> SystemCash { get; set; }
        public Nullable<decimal> ActualCash { get; set; }
        public Nullable<int> C1 { get; set; }
        public Nullable<int> C5 { get; set; }
        public Nullable<int> C10 { get; set; }
        public Nullable<int> C20 { get; set; }
        public Nullable<int> C50 { get; set; }
        public Nullable<int> C100 { get; set; }
        public Nullable<int> C200 { get; set; }
        public Nullable<int> C500 { get; set; }
        public Nullable<decimal> CashDiff { get; set; }
        public Nullable<int> CashCount { get; set; }
        public Nullable<decimal> CreditAmt { get; set; }
        public Nullable<decimal> DebitAmt { get; set; }
        public Nullable<int> DebitCnt { get; set; }
        public Nullable<decimal> ReturnAmt { get; set; }
        public Nullable<int> ReturnCnt { get; set; }
        public Nullable<decimal> DeleteAmt { get; set; }
        public Nullable<int> DeleteCnt { get; set; }
        public Nullable<decimal> OnAccAmt { get; set; }
        public Nullable<int> OnAccCnt { get; set; }
        public Nullable<decimal> Cust1Amt { get; set; }
        public Nullable<int> Cust1Cnt { get; set; }
        public Nullable<decimal> Cust2Amt { get; set; }
        public Nullable<int> Cust2Cnt { get; set; }
        public Nullable<int> CreditCnt { get; set; }
        public int Dataid { get; set; }
        public Nullable<decimal> Cash_Collection { get; set; }
    }
}
