//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PI_TimeTable
    {
        public int Id { get; set; }
        public string PI_KeyWord { get; set; }
        public string PI_Description { get; set; }
        public string Days { get; set; }
        public string PI_DateTime { get; set; }
        public string LocationID { get; set; }
        public string StorageID { get; set; }
        public string TerminalID { get; set; }
        public bool ConRead { get; set; }
    }
}
