//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POSException
    {
        public int POSExceptionID { get; set; }
        public string ExceptionType { get; set; }
        public string ExceptionModule { get; set; }
        public string ExceptionCode { get; set; }
        public string Source { get; set; }
        public string Message { get; set; }
        public string QueryString { get; set; }
        public string TargetSite { get; set; }
        public string StrackTrace { get; set; }
        public string ServerName { get; set; }
        public string UserAgent { get; set; }
        public string UserIP { get; set; }
        public string UserAuthentication { get; set; }
        public string UserName { get; set; }
        public string RequestUrl { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public System.DateTime RowCreatedDateTime { get; set; }
    }
}
